### ISSUE TITLE
binding.Errors does not implement validation.Errors 

### ISSUE THREAD

**Issue by techjanitor** [jamieomatthews/validation#4]
I can't seem to use this with the given example and binding:

```
cannot use errors (type binding.Errors) as type validation.Errors in function argument:
    binding.Errors does not implement validation.Errors (missing Add method)
impossible type assertion:
    *binding.Errors does not implement validation.Errors (missing Add method)
```

It's the latest binding (from today)

Also what is the interface part in NewValidation?

Thanks!

**Comment by jamieomatthews** [comment]
Are you using this in conjunction with Martini Binding?  If so, go get -u the binding package, because that's been updated to use my interface

**Comment by techjanitor** [comment]
Yes. I just deleted everything and got them again to make sure.

```
 cannot use errors (type "github.com/martini-contrib/binding".Errors) as type validation.Errors in function argument:
    "github.com/martini-contrib/binding".Errors does not implement validation.Errors (Add method has pointer receiver)
```

``` go
func (tf ThreadForm) Validate(errors binding.Errors, req *http.Request) binding.Errors {

        v := validation.NewValidation(errors, user)

        v.Validate(&tf.Title).Range(5, 45).TrimSpace()
        v.Validate(&tf.Comment).MaxLength(5000).TrimSpace()

        return *v.Errors.(*binding.Errors)
}
```

**Comment by superduper** [comment]
Hello! Any solution for that?

**Comment by jerbob92** [comment]
I still have this issue. 
I'm also wondering where the "user" variable is coming from in the example...

What do I actually have to pass in there?

**Comment by jamieomatthews** [comment]
@techjanitor @superduper  I know this issue is super old, I've been working on other projects, but I finally got time to come back to this!  

@techjanitor you need to pass errors in by reference, eg

``` go
 v := validation.NewValidation(&errors, user)
```

@jerbob92 that was also a typo from a difference of what struct I was using in the readme vs the tests.  I've updated it to use the contactRequest that's being validated.  

Let me know if you guys have more issues!

**Comment by jerbob92** [comment]
Thanks, that works!
